### ISSUE TITLE
ag_load_script not doing anything:  Payload generator + arsenal kit

### ISSUE THREAD

**Issue by eddiezab** [Cobalt-Strike/sleep_python_bridge#10]
Hello,

I'm unsure what I may be doing wrong, I am unable to get the payload generator to generate a payload using the arsenal kit. What I've done:

I've dropped the contents of the generated `dist` folder (`arsenal_kit.cna` & `artifact/**`) into the same folder with the payload_scripts.cna, and renamed the `arsenal_kit.cna` to `payload_scripts.cna`.

However when I run the payload generator I appear to get a vanilla payload as opposed to the customized payload. 

In this first screenshot is the metadata of the payload generator beacon.
![Payload Generator Beacon](https://user-images.githubusercontent.com/2179170/230770451-326b7b2f-e990-4133-bf20-871fcb118980.png)

This beacon was generated using the GUI with arsenal kit loaded. In it you can see the contents of the `resource.rc` being added as additional attributes as expected, indicating the arsenal kit was loaded.
![GUI Generated Beacon](https://user-images.githubusercontent.com/2179170/230770411-fc442561-bfec-4b04-91be-11a3ab19723b.png)

Am I doing something wrong? Is this a bug? 

Thanks!

**Comment by eddiezab** [comment]
Huzzah! Behold it now works! I appreciate the effort you put in to fix this.

**Comment by chris-thorpe** [comment]
Thank you for validating the fix.

The fix has been merged into the main line.  See the following commit:  https://github.com/Cobalt-Strike/sleep_python_bridge/commit/c137fea9338b50728b802841baa4e0cfd17dcfba
