### ISSUE TITLE
Support for Cobalt Strike 4.8

### ISSUE THREAD

**Issue by don-silvia** [Cobalt-Strike/sleep_python_bridge#13]
I'm getting "Error: Cobalt Strike JAR file not found" when running striker.py against Cobalt Strike 4.8.  I see that connectTeamserver is looking for cobaltstrike.jar, but that file doesn't exist in 4.8.  Is there a workaround?

**Comment by chris-thorpe** [comment]
The striker.py script is not meant to be run directly and is only meant to provide helper functions, see the 4 example *.py scripts at the top level of the project on how to use the CSConnector().  Basically what is missing in the striker.py CSConnector() is the cs_directory information, which will set the path to the cobaltstrike.jar file.

**Comment by chris-thorpe** [comment]
Then you are not supplying the correct path to where Cobalt Strike is installed on your Linux system as there is a cobaltstrike.jar file for all cobalt strike installations.  This check is there to validate the user is supplying a valid path to the installation.  Also if it is not clear these python scripts are only supported on Linux systems.

Using the example.py script in the project this is how you would run it, making sure the Cobalt Strike team server is running on the <hostname>.

python3 ./example.py <hostname> 50050 <user> <password> /path/to/cobaltstrike
